### ISSUE TITLE
main.cpp has missing semicolon

### ISSUE THREAD

**Issue by SahilK-027** [wolverin0121/TEST-2#1]
## At line number 5
<img width="348" alt="Screenshot 2023-02-24 at 10 49 13 PM" src="https://user-images.githubusercontent.com/104154041/221245297-49727dfd-c111-4dcb-9092-eb5e0731f3f3.png">

**Comment by wolverin0121** [comment]
Nice observation. You can work on this issue.

**Comment by SahilK-027** [comment]
Ok I'll work on fixing this
